
tiff("networks.tiff",compression="lzw",units="in",height=8,width=8,res=800)
layout(matrix(1:4,nrow=2,ncol=2,byrow=T))
par(mar=c(0,0,0,0))
source("Linear network.R")
plot(linearLandscape,col="dodgerblue",layout=layout.auto(linearLandscape),vertex.size=node.size*17)
Corner_text("Linear",location="top")
source("Watershed network.R")
plot(riverLandscape,col="dodgerblue",layout=layout.auto(riverLandscape),vertex.size=node.size*17)
Corner_text("Dendritic",location="top")
source("Star network.R")
plot(starLandscape,col="dodgerblue",layout=layout.reingold.tilford(starLandscape,circular=T),vertex.size=node.size*17)
Corner_text("Star",location="top")
source("Complex network.R")
plot(complexLandscape,col="dodgerblue",layout=layout.auto(complexLandscape),vertex.size=node.size*17)
Corner_text("Complex",location="top")
dev.off()
