---
title: "Equivalent Productivities"
author: "Colin"
date: "February 7, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)


#base ricker setup
alpha <- 20
beta <- 5e-3
cv <- 0.1
stock <- 0:1000
rec_mean <- alpha*stock*exp(-beta*stock)
rec.obs <- pmax(0,rnorm(length(stock),mean=rec_mean,sd=rec_mean*cv))

ricker <-function(Nadults){alpha*Nadults*exp(-beta*Nadults)}

plot(stock,rec_mean,type="l",ylim=c(0,max(rec.obs)))
points(stock,rec.obs,pch=21,bg="grey50")


```

Have to model a simple scenario with 5 populations. In one scenario, all populations have the same alpha and beta, and in second, both alpha and beta must vary. However, total population productivity must be the same.

Basically we are looking for the ricker curves of each metapopulation to match when all metapopulations are harvested equally.

```{r df1}
#function that calculates carrying capacity
k <- function(alpha,beta){
  log(alpha)/beta
}

beta <- function(alpha,k){
  log(alpha)/k
}

alpha <- function(beta,k){
  exp(beta*k)
}

#pop/n 1:5 of metapop/n 1
df1 <- c(1:5)
df1 <- data.frame(df1,alpha=rep(20,5))

df1$beta <- beta(df1$alpha, 1000)
df1$k1 <- k(df1$alpha,df1$beta)
stocks1 <- data.frame(pop1=rep(99,1001),pop2=rep(99,1001),pop3=rep(99,1001),pop4=rep(99,1001),pop5=rep(99,1001))

for(i in 1:5){
  stocks1[,i] <- df1$k1[i]*seq(0,1,by=0.001)
}


rec_mean1 <- data.frame(pop1=rep(99,1001),pop2=rep(99,1001),pop3=rep(99,1001),pop4=rep(99,1001),pop5=rep(99,1001))

for(i in 1:5){
  rec_mean1[,i] <- df1$alpha[i]*stocks1[,i]*exp(-df1$beta[i]*stocks1[,i])
}

rec_mean1 <- rec_mean1 %>% mutate(meta = pop1+pop2+pop3+pop4+pop5)
stocks1 <- stocks1 %>% mutate(total = pop1+pop2+pop3+pop4+pop5)

ggplot(rec_mean1, aes(x=stocks1$total, y=meta))+
  geom_line()
```


```{r df2}
#carrying capacity of the metapopulation remains essentially the same if you use rnorm to sample alphas while keeping the mean alpha the same as the homogenous metapopulation
#have to be careful that the range of stock sizes you run are proportional to the carrying capacity of the sub population
#pop/n 1:5 of metapop/n 2
df2 <- c(1:5)
df2 <- data.frame(df2,k=c(1000,200,1800,1500,500))
df2$beta <- rep(0.002995732,5)
df2$alpha <- alpha(df2$beta, df2$k)
stocks2 <- data.frame(pop1=rep(99,1001),pop2=rep(99,1001),pop3=rep(99,1001),pop4=rep(99,1001),pop5=rep(99,1001))

for(i in 1:5){
  stocks2[,i] <- df2$k[i]*seq(0,1,by=0.001)
}

rec_mean2 <- data.frame(pop1=rep(99,1001),pop2=rep(99,1001),pop3=rep(99,1001),pop4=rep(99,1001),pop5=rep(99,1001))

for(i in 1:5){
  rec_mean2[,i] <- df2$alpha[i]*stocks2[,i]*exp(-df2$beta[i]*stocks2[,i])
}

rec_mean2 <- rec_mean2 %>% mutate(meta = pop1+pop2+pop3+pop4+pop5)
stocks2 <- stocks2 %>% mutate(total = pop1+pop2+pop3+pop4+pop5)

ggplot(rec_mean2, aes(x=stocks2$total, y=meta))+
  geom_line()

```


```{r df3}
#carrying capacity of the metapopulation remains essentially the same if you use rnorm to sample alphas while keeping the mean alpha the same as the homogenous metapopulation
#have to be careful that the range of stock sizes you run are proportional to the carrying capacity of the sub population
#pop/n 1:5 of metapop/n 2
df3 <- c(1:5)
df3 <- data.frame(df3,k=c(1000,200,1800,1500,500))
df3$alpha <- rep(20,5)
df3$beta <- beta(df3$alpha, df3$k)
stocks3 <- data.frame(pop1=rep(99,1001),pop2=rep(99,1001),pop3=rep(99,1001),pop4=rep(99,1001),pop5=rep(99,1001))

for(i in 1:5){
  stocks3[,i] <- df3$k[i]*seq(0,1,by=0.001)
}

rec_mean3 <- data.frame(pop1=rep(99,1001),pop2=rep(99,1001),pop3=rep(99,1001),pop4=rep(99,1001),pop5=rep(99,1001))

for(i in 1:5){
  rec_mean3[,i] <- df3$alpha[i]*stocks3[,i]*exp(-df3$beta[i]*stocks3[,i])
}

rec_mean3 <- rec_mean3 %>% mutate(meta = pop1+pop2+pop3+pop4+pop5)
stocks3 <- stocks3 %>% mutate(total = pop1+pop2+pop3+pop4+pop5)

ggplot(rec_mean3, aes(x=stocks3$total, y=meta))+
  geom_line()

#plotting all of the lines
ggplot(rec_mean1, aes(x=stocks3$total, y=meta, colour="uniform"))+
  theme_classic()+
  geom_line()+
  geom_line(data=rec_mean2, aes(x=stocks3$total, y=meta, colour="alpha"), alpha=0.3, size=3)+
  geom_line(data=rec_mean3, aes(x=stocks3$total, y=meta, colour="beta"), alpha=0.3, size=5)+
  scale_color_manual(values=c("beta"="red","uniform"="black","alpha"="green"))
  




```







